/*
Ýlk olarak veritabanýný oluþturacaðýnýz kýsmý seçip çalýþtrýn ve yenileyin.
ÝLETÝÞÝM EÐÝTÝM TAKIM TÝYATRO FÝLM DÝZÝ ÖDÜLTABLOSU PROGRAM REKLAM tablolarýný seçip çalýþtýrýn ve yenileyin.
Son kýsým da OYUNCULAR tablosunu seçip çalýþtýrýn ve yenileyin böylece OYUNCUMENAJERI veritabanýný oluþturursunuz.
*/
/*OYUNCUMENAJERI veritabanýný oluþturma*/
CREATE DATABASE OYUNCUMENAJERI


/*ÝLETÝÞÝM TABLOSU VE VERÝ GÝRME*/
CREATE TABLE ILETISIM( 
ID INT IDENTITY(1,1)  NOT NULL PRIMARY KEY, 
TELEFON CHAR(10)  NOT NULL, 
MAIL VARCHAR(25)  NOT NULL,
INSTAGRAM VARCHAR(20),
TWITTER VARCHAR(20))
INSERT INTO ILETISIM (TELEFON,MAIL,INSTAGRAM,TWITTER) VALUES ('5553852463','oguzhan@deneme.com','oguzhan05','oguzhan05')
INSERT INTO ILETISIM (TELEFON,MAIL,INSTAGRAM,TWITTER) VALUES ('5375169149','aylin@deneme.com','26aylin','26aylin')
INSERT INTO ILETISIM (TELEFON,MAIL,INSTAGRAM,TWITTER) VALUES ('5349106933','tugba@deneme.com','tugba0','tugba0')
INSERT INTO ILETISIM (TELEFON,MAIL,INSTAGRAM,TWITTER) VALUES ('5439894233','eray@deneme.com','eray56','eray56')
INSERT INTO ILETISIM (TELEFON,MAIL,INSTAGRAM,TWITTER) VALUES ('5349377724','buglem@deneme.com','buglem89','buglem89')
INSERT INTO ILETISIM (TELEFON,MAIL,INSTAGRAM,TWITTER) VALUES ('5348242021','tuna@deneme.com','tuna65','tuna65')
INSERT INTO ILETISIM (TELEFON,MAIL,INSTAGRAM,TWITTER) VALUES ('5547592883','onur@deneme.com','onurrr5','onurr5')


/*EÐÝTÝM TABLOSU VE VERÝ GÝRME*/
CREATE TABLE EGITIM(
ID INT IDENTITY(1,1)  NOT NULL PRIMARY KEY,
OKULADI VARCHAR(60)  NOT NULL,
BOLUMADI VARCHAR(60) NOT NULL,
MEZUNYILI INT NOT NULL)
INSERT INTO EGITIM (OKULADI,BOLUMADI,MEZUNYILI) VALUES ('Anadolu Üniversitesi Devlet Konservatuarý','Sahne Sanatlarý Bölümü Oyunculuk Ana Sanat Dalý','2018')
INSERT INTO EGITIM (OKULADI,BOLUMADI,MEZUNYILI) VALUES ('Ýstanbul Üniversitesi Devlet Konservatuarý','Sahne Sanatlarý Bölümü Tiyatro Ana Sanat Dalý','2017')
INSERT INTO EGITIM (OKULADI,BOLUMADI,MEZUNYILI) VALUES ('Beykent Üniversitesi','Güzel Sanatlar Fakültesi Oyunculuk Bölümü','2021')
INSERT INTO EGITIM (OKULADI,BOLUMADI,MEZUNYILI) VALUES ('Mimar Sinan Güzel Sanatlar Anadolu Lisesi','Tiyatro Bölümü','2019')
INSERT INTO EGITIM (OKULADI,BOLUMADI,MEZUNYILI) VALUES ('Anadolu Üniversitesi Devlet Konservatuarý','Sahne Sanatlarý Bölümü Oyunculuk Ana Sanat Dalý','2020')
INSERT INTO EGITIM (OKULADI,BOLUMADI,MEZUNYILI) VALUES ('Beykent Üniversitesi','Güzel Sanatlar Fakültesi Oyunculuk Bölümü','2020')



/*TAKIM TABLOSU VE VERÝ GÝRME*/
CREATE TABLE TAKIM(
ID INT IDENTITY(1,1)  NOT NULL PRIMARY KEY,
REKLAMSORUMLUSU VARCHAR(50),
HUKUKSORUMLUSU VARCHAR(50) NOT NULL,
BASINDANISMANI VARCHAR(50))
INSERT INTO TAKIM (REKLAMSORUMLUSU,HUKUKSORUMLUSU,BASINDANISMANI) VALUES ('Yaþar SAVURGAN','Nazlý ÖRNEK','Birsen AKKOR')
INSERT INTO TAKIM (REKLAMSORUMLUSU,HUKUKSORUMLUSU,BASINDANISMANI) VALUES ('Necdet ERÇAM','Irmak HAMÝDÝ','Muhammed Ali ABDULLAH')
INSERT INTO TAKIM (REKLAMSORUMLUSU,HUKUKSORUMLUSU,BASINDANISMANI) VALUES ('Ömer Faruk KOCANOÐLU','Irmak HAMÝDÝ','Elif ÖZÇELÝKBAÞ')
INSERT INTO TAKIM (REKLAMSORUMLUSU,HUKUKSORUMLUSU,BASINDANISMANI) VALUES ('Mira TÜTER','Ada VAPUR','Can DOLAR')
INSERT INTO TAKIM (REKLAMSORUMLUSU,HUKUKSORUMLUSU,BASINDANISMANI) VALUES ('Mira TÜTER','Ýsa BÖLÜK','Muhammed Ali ABDULLAH')



/*TÝYATRO TABLOSU VE VERÝ GÝRME*/
CREATE TABLE TIYATRO(
ID INT IDENTITY(1,1)  NOT NULL PRIMARY KEY,
TIYATROADI VARCHAR(50) NOT NULL,
YIL INT NOT NULL)
INSERT INTO TIYATRO (TIYATROADI,YIL) VALUES ('Aldatanlar Kulübü','2023')
INSERT INTO TIYATRO (TIYATROADI,YIL) VALUES ('Gelecek Kaygýsý','2022')
INSERT INTO TIYATRO (TIYATROADI,YIL) VALUES ('Sosyal Medya','2023')



/*FÝLM TABLOSU VE VERÝ GÝRME*/
CREATE TABLE FILM(
ID INT IDENTITY(1,1)  NOT NULL PRIMARY KEY,
FILMADI VARCHAR(50) NOT NULL,
YIL INT NOT NULL)
INSERT INTO FILM (FILMADI,YIL) VALUES ('Cadý Okulu','2023')
INSERT INTO FILM (FILMADI,YIL) VALUES ('Katil','2021')
INSERT INTO FILM (FILMADI,YIL) VALUES ('Sticker Avcýsý','2022')
INSERT INTO FILM (FILMADI,YIL) VALUES ('Yazdýðým Þiirdin','2023')
INSERT INTO FILM (FILMADI,YIL) VALUES ('Uyumayanlar','2023')



/*DÝZÝ TABLOSU VE VERÝ GÝRME*/
CREATE TABLE DIZI(
ID INT IDENTITY(1,1)  NOT NULL PRIMARY KEY,
DIZIADI VARCHAR(50) NOT NULL,
YIL VARCHAR(10) NOT NULL,
BOLUMSAYISI INT NOT NULL)
INSERT INTO DIZI (DIZIADI,YIL,BOLUMSAYISI) VALUES ('Marjinal Gün','2021','25')
INSERT INTO DIZI (DIZIADI,YIL,BOLUMSAYISI) VALUES ('Aldatmak da suç','2022','3')
INSERT INTO DIZI (DIZIADI,YIL,BOLUMSAYISI) VALUES ('Kusursuz Katil','2021-2022','32')
INSERT INTO DIZI (DIZIADI,YIL,BOLUMSAYISI) VALUES ('Masalýmýn Gargameli','2020','15')
INSERT INTO DIZI (DIZIADI,YIL,BOLUMSAYISI) VALUES ('Güzeliðin Kusuru','2019-2021','60')



/*ÖDÜLTABLOSU VE VERÝ GÝRME*/
CREATE TABLE ODUL(
ID INT IDENTITY(1,1)  NOT NULL PRIMARY KEY,
ODULADI VARCHAR(100) NOT NULL,
YIL INT NOT NULL)
INSERT INTO ODUL (ODULADI,YIL) VALUES ('Pink Kelebek En Ýyi Kadýn Oyuncu','2021')
INSERT INTO ODUL (ODULADI,YIL) VALUES ('Pink Kelebek En Ýyi Erkek Oyuncu','2021')
INSERT INTO ODUL (ODULADI,YIL) VALUES ('4. Uluslararasý Film Festivali En Ýyi Film Kadýn Oyuncu','2022')
INSERT INTO ODUL (ODULADI,YIL) VALUES ('4. Uluslararasý Film Festivali En Ýyi Film Erkek Oyuncu','2022')
INSERT INTO ODUL (ODULADI,YIL) VALUES ('Pink Kelebek En Ýyi Kadýn Oyuncu','2022')
INSERT INTO ODUL (ODULADI,YIL) VALUES ('Pink Kelebek En Ýyi Erkek Oyuncu','2022')



/*PROGRAM TABLOSU VE VERÝ GÝRME*/
CREATE TABLE PROGRAM(
ID INT IDENTITY(1,1)  NOT NULL PRIMARY KEY,
PROGRAMADI VARCHAR(40) NOT NULL,
YIL VARCHAR(15) NOT NULL)
INSERT INTO PROGRAM (PROGRAMADI,YIL) VALUES ('Sabahýn Körü','2019-günümüz')
INSERT INTO PROGRAM (PROGRAMADI,YIL) VALUES ('Dedikodunun Peþinde','2017-günümüz')
INSERT INTO PROGRAM (PROGRAMADI,YIL) VALUES ('Saðlýklý Yaþam','2022-günümüz')
INSERT INTO PROGRAM (PROGRAMADI,YIL) VALUES ('Gençlerin Sesi','2020-günümüz')
INSERT INTO PROGRAM (PROGRAMADI,YIL) VALUES ('Z Kuþaðý','2020-2021')



/*REKLAM TABLOSU VE VERÝ GÝRME*/
CREATE TABLE REKLAM(
ID INT IDENTITY(1,1)  NOT NULL PRIMARY KEY,
MARKA VARCHAR(15) NOT NULL)
INSERT INTO REKLAM (MARKA) VALUES ('Demo')
INSERT INTO REKLAM (MARKA) VALUES ('ASN')
INSERT INTO REKLAM (MARKA) VALUES ('Pink')
INSERT INTO REKLAM (MARKA) VALUES ('Turkcell')
INSERT INTO REKLAM (MARKA) VALUES ('Labne')



/*OYUNCULAR TABLOSU VE VERÝ GÝRME*/
CREATE TABLE OYUNCULAR(
ID INT IDENTITY(1,1)  NOT NULL PRIMARY KEY,
AD VARCHAR(50) NOT NULL,
SOYAD VARCHAR(10) NOT NULL,
CINSIYET VARCHAR(1) NOT NULL,
DOGUMGUNU DATE NOT NULL,
ACIKADRES VARCHAR(250) NOT NULL,
ILETISIMID INT FOREIGN KEY REFERENCES ILETISIM(ID) NOT NULL,
EGITIMID INT FOREIGN KEY REFERENCES EGITIM(ID),
TAKIMID INT FOREIGN KEY REFERENCES TAKIM(ID) NOT NULL,
FILMID INT FOREIGN KEY REFERENCES FILM(ID),
TIYATROID INT FOREIGN KEY REFERENCES TIYATRO(ID),
DIZIID INT FOREIGN KEY REFERENCES DIZI(ID),
PROGRAMID INT FOREIGN KEY REFERENCES PROGRAM(ID),
ODULID INT FOREIGN KEY REFERENCES ODUL(ID),
REKLAMID INT FOREIGN KEY REFERENCES REKLAM(ID),
ALINANUCRET MONEY NOT NULL)
INSERT INTO OYUNCULAR (AD,SOYAD,CINSIYET,DOGUMGUNU,ACIKADRES,ILETISIMID,EGITIMID,TAKIMID,FILMID,TIYATROID,DIZIID,PROGRAMID,ODULID,REKLAMID,ALINANUCRET) 
VALUES ('Oðuzhan','UZUNKAYA','E','1993.01.21','ÝHSANÝYE MERKEZ MAH.4375.. SOKAK NO:607 100231 GÖLCÜK/KOCAELÝ','1','2','5','2',NULL,'2','1',NULL,NULL,'20640')
INSERT INTO OYUNCULAR (AD,SOYAD,CINSIYET,DOGUMGUNU,ACIKADRES,ILETISIMID,EGITIMID,TAKIMID,FILMID,TIYATROID,DIZIID,PROGRAMID,ODULID,REKLAMID,ALINANUCRET) 
VALUES ('Aylin','TAÞHAN','K','1999.10.19','ATAMER MAH.2581. SOKAK NO:529 96650 KONAK/ÝZMÝR','2','5','1','1','2',NULL,NULL,NULL,'5','20640')
INSERT INTO OYUNCULAR (AD,SOYAD,CINSIYET,DOGUMGUNU,ACIKADRES,ILETISIMID,EGITIMID,TAKIMID,FILMID,TIYATROID,DIZIID,PROGRAMID,ODULID,REKLAMID,ALINANUCRET) 
VALUES ('Tuðba','UZUNBAYIR','K','2000.10.19','FATIH MAH.PLEVNE CADDESÝ SOKAK NO:563 119342 SANCAKTEPE/ÝSTANBUL','3','6','4','3','1','5',NULL,'1','1','20640')
INSERT INTO OYUNCULAR (AD,SOYAD,CINSIYET,DOGUMGUNU,ACIKADRES,ILETISIMID,EGITIMID,TAKIMID,FILMID,TIYATROID,DIZIID,PROGRAMID,ODULID,REKLAMID,ALINANUCRET) 
VALUES ('Eray','BOZNA','E','1999.05.19','SÜMER MAH.440. SOKAK NO:506 96717 KONAK/ÝZMÝR','4','5','3','4',NULL,'2',NULL,'6',NULL,'20640')
INSERT INTO OYUNCULAR (AD,SOYAD,CINSIYET,DOGUMGUNU,ACIKADRES,ILETISIMID,EGITIMID,TAKIMID,FILMID,TIYATROID,DIZIID,PROGRAMID,ODULID,REKLAMID,ALINANUCRET) 
VALUES ('Buðlem','ÖZDEK','K','2001.05.19','SEVGÝ MAH.87. SOKAK NO:377 96596 GAZÝEMÝR/ÝZMÝR','5','3','2','2','1','3','5','5','2','20640')
INSERT INTO OYUNCULAR (AD,SOYAD,CINSIYET,DOGUMGUNU,ACIKADRES,ILETISIMID,EGITIMID,TAKIMID,FILMID,TIYATROID,DIZIID,PROGRAMID,ODULID,REKLAMID,ALINANUCRET) 
VALUES ('Tuna','KUZUN','E','2000.07.12','FATÝH MAH.2757. SOKAK NO:856 116027 KIRIKKALE MERKEZ/KIRIKKALE','6','5','1','5',NULL,'1',NULL,'4','3','20640')
INSERT INTO OYUNCULAR (AD,SOYAD,CINSIYET,DOGUMGUNU,ACIKADRES,ILETISIMID,EGITIMID,TAKIMID,FILMID,TIYATROID,DIZIID,PROGRAMID,ODULID,REKLAMID,ALINANUCRET) 
VALUES ('Onur','KIRIT','E','1999.05.22','YENÝ MAH.BADEMKENT KÜME EVLERÝ SOKAK NO:662 88689 ACIPAYAM/DENÝZLÝ','7','3','4','1','3','3',NULL,NULL,NULL,'20640')
